/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NewsRouteImport } from './routes/news'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BooksRouteImport } from './routes/books'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsSlugRouteImport } from './routes/tools.$slug'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as BooksIdRouteImport } from './routes/books.$id'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSlugRoute = ToolsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ToolsRoute,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InsightsRoute,
} as any)
const BooksIdRoute = BooksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BooksRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/books': typeof BooksRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/insights': typeof InsightsRouteWithChildren
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tools': typeof ToolsRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/books/$id': typeof BooksIdRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/books': typeof BooksRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/insights': typeof InsightsRouteWithChildren
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tools': typeof ToolsRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/books/$id': typeof BooksIdRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/books': typeof BooksRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/insights': typeof InsightsRouteWithChildren
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tools': typeof ToolsRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/books/$id': typeof BooksIdRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/books'
    | '/contact'
    | '/faq'
    | '/insights'
    | '/news'
    | '/privacy'
    | '/sitemap.xml'
    | '/tools'
    | '/blog/$slug'
    | '/books/$id'
    | '/insights/$slug'
    | '/tools/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/books'
    | '/contact'
    | '/faq'
    | '/insights'
    | '/news'
    | '/privacy'
    | '/sitemap.xml'
    | '/tools'
    | '/blog/$slug'
    | '/books/$id'
    | '/insights/$slug'
    | '/tools/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/books'
    | '/contact'
    | '/faq'
    | '/insights'
    | '/news'
    | '/privacy'
    | '/sitemap.xml'
    | '/tools'
    | '/blog/$slug'
    | '/books/$id'
    | '/insights/$slug'
    | '/tools/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  BooksRoute: typeof BooksRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  InsightsRoute: typeof InsightsRouteWithChildren
  NewsRoute: typeof NewsRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ToolsRoute: typeof ToolsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$slug': {
      id: '/tools/$slug'
      path: '/$slug'
      fullPath: '/tools/$slug'
      preLoaderRoute: typeof ToolsSlugRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/books/$id': {
      id: '/books/$id'
      path: '/$id'
      fullPath: '/books/$id'
      preLoaderRoute: typeof BooksIdRouteImport
      parentRoute: typeof BooksRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface BooksRouteChildren {
  BooksIdRoute: typeof BooksIdRoute
}

const BooksRouteChildren: BooksRouteChildren = {
  BooksIdRoute: BooksIdRoute,
}

const BooksRouteWithChildren = BooksRoute._addFileChildren(BooksRouteChildren)

interface InsightsRouteChildren {
  InsightsSlugRoute: typeof InsightsSlugRoute
}

const InsightsRouteChildren: InsightsRouteChildren = {
  InsightsSlugRoute: InsightsSlugRoute,
}

const InsightsRouteWithChildren = InsightsRoute._addFileChildren(
  InsightsRouteChildren,
)

interface ToolsRouteChildren {
  ToolsSlugRoute: typeof ToolsSlugRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsSlugRoute: ToolsSlugRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  BooksRoute: BooksRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  InsightsRoute: InsightsRouteWithChildren,
  NewsRoute: NewsRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ToolsRoute: ToolsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
